class Employee {
  int id;
  String amharic_name;
  String oromic_name;
  String oromic_position;
  String path;
  String position;
  String office;
  Employee(this.id, this.amharic_name, this.oromic_name, this.oromic_position,
      this.path, this.position, this.office);
}

List<Employee> Employees = [
  Employee(1, "ያዜ የሻምበል ታፈረ", "Yaze Yeshamber Terefe", "Hogganaa Damee",
      "shambel_tefera.png", "የቅርንጫፍ ስራ አስኪያጅ", "20"),
  Employee(2, "ታንጉት አእምሮ ፈንታ", "Tangut Aymro Fanta",
      "Barreessaa Hojii Raawwachiiftuu", "", "ኤክስኪዩቲቭ ሴክሬታሪ ", "20"),
  Employee(
      3,
      "ጌትነት አድማሱ ጌታሁን",
      "Getnat Admasu Getahun",
      "Daarektarri Tajaajila Mirkaneessuu fi Hayyama Konkolaataa",
      "getnet_admasu.png",
      "የተሸከርካሪ ብቃት ማረጋገጥና ፈቃድ አገልግሎት ዳይሬክተር",
      "21"),
  Employee(
      4,
      "እንዳለ ባህሩ ተሰማ",
      "Endale Bahiru Tesema",
      "Hogganaa garee gahumsa konkolaataa",
      "endale_birhanu.png",
      "የተሽከርካሪ  ብቃት ማረጋገጥ ቡድን መሪ",
      "35"),
  Employee(
      5,
      "ታምራት አበራ ኃይሌ",
      "Tamirat Abarra Haayile",
      "Hogganaa garee gahumsa konkolaataa",
      "tamirat_abera.png",
      "የተሽከርካሪ  ብቃት ማረጋገጥ ቡድን መሪ",
      "21"),
  Employee(
      6,
      "ሃብታሙ ወርቃለም አሊ",
      "Habtamu Warqaalam Ali",
      "Ogeessa tajaajila hayyama konkolaataa",
      "habtamu_werkalema.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
      "3"),
  Employee(
      7,
      "ዋሲሁን መላኩ ባህሩ",
      "Wasihun Malaku Bahiru",
      "Ogeessa tajaajila hayyama konkolaataa",
      "wasihun_melaku.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
      "6"),
  Employee(
      8,
      "መልካምሰዉ አቤ መንግስቱ",
      "MalkamSaw Abbe Mengistu",
      "Ogeessa tajaajila hayyama konkolaataa",
      "melkam_sewu.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
      "5"),
  Employee(
      9,
      "አዳነች ጌጡ መብራቴ",
      "Adanach Gexu Mabrate",
      "Ogeessa tajaajila hayyama konkolaataa",
      "adanech_getu.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
      "8"),
  Employee(
      10,
      "አሚር በህጃ ናስር",
      "Amir Bahaj Nasir",
      "Ogeessa tajaajila hayyama konkolaataa",
      "amir_behaj.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
      "4"),
  Employee(
      11,
      "ታደለ አባተ ካሳ",
      "Tadele Abate Kasa",
      "Ogeessa tajaajila hayyama konkolaataa",
      "tadla_abate.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
      "7"),
  Employee(
      12,
      "ኤደን ተ/ሃይማኖት ኃይሌ",
      "Edan T/Hayimanot Hayile",
      "Ogeessa tajaajila hayyama konkolaataa",
      "eden_tekle.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
      "10"),
  Employee(
      13,
      "ህብስት አድማሱ አድገህ",
      "Hibist Admaasu Adgah",
      "Ogeessa tajaajila hayyama konkolaataa",
      "hibest_admasu.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
      "9"),
  Employee(
      14,
      "ፈድሉ ኑረዲን መሀመድ",
      "Fadila Nuradin Mahammad",
      "Ogeessa inspeekshinii teeknikaa konkolaataa",
      "fedle_nuredin.png",
      "የተሽከርካሪ የቴክኒክ ምርመራ ባለሙያ ",
      "11"),
  Employee(
      15,
      "ኤልያስ ስርዓቱ ፉጃጋ",
      "Eliyas Siriatu Fajiga",
      "Ogeessa inspeekshinii teeknikaa konkolaataa",
      "",
      "የተሽከርካሪ የቴክኒክ ምርመራ ባለሙያ ",
      "11"),
  Employee(
      16,
      "ቤተልሄም ጥላሁን ወ/ጊዮርጊስ",
      "Betlihem Xilahun W/Giorgis",
      "Ogeessa inspeekshinii teeknikaa konkolaataa",
      "",
      "የተሽከርካሪ የቴክኒክ ምርመራ ባለሙያ ",
      "11"),
  Employee(
      17,
      "ቤኩማ ገመቺስ ሂርጳ",
      "Beekuma Gammmachiis Hirphoo",
      "Ogeessa inspeekshinii teeknikaa konkolaataa",
      "",
      "የተሽከርካሪ የቴክኒክ ምርመራ ባለሙያ ",
      "11"),
  Employee(18, "መዓዛ አምሳሉ ቸሩ", "", "Ogeessa inspeekshinii teeknikaa konkolaataa",
      "meaza_amsalu.png", "የተሽከርካሪ የቴክኒክ ምርመራ ባለሙያ ", "11"),
  Employee(19, "ሚሊዮን አዲሱ በላይ", "Miliyon Addisu Balaay",
      "Hojjetaa galmee fi kuusaa", "", "የሪከርድና ማህደር ሠራተኛ", "36"),
  Employee(
      20,
      "ቃልኪዳን አሊ አህመድ",
      "Qaalkidaan Ali Ahmad",
      "Qindeessaa Deetaa Konkolaataa / Encoderii Deetaa",
      "kalkidan_ali.png",
      "የተሸከርካሪ መረጃ አጠናቃሪ ባለሙያ/ የዳታ ኢንኮደር ባለሙያ ",
      "34"),
  Employee(
      21,
      "ሳሙኤል ግዛዉ ሞረዳ",
      "Samuel Gizaw Moroda",
      "Ogeessa tajaajila odeeffannoo",
      "samuel_gizaw.png",
      "የመረጃ አገልግሎት ባለሙያ ",
      "30"),
  Employee(22, "ጀማል ባርቀዳ በሽር", "Jamal Barqada Bashir",
      "Bulchaa Kuusaa Deetaa fi Sirna", "", "ዳታ ቤዝ እና ሲስተም አድሚኒስትሬተር ", ""),
  Employee(
      23,
      "ነጋ ብሩክ ሀብቴ",
      "Naggaa Biruk Habtee",
      "Ogeessa sakatta’iinsa hatattamaa konkolaataa fi mirkaneessa dhaabbilee",
      "",
      "የተሽከርካሪ  ድንገተኛ ምርመራና ተቋማት ብቃት ማረጋገጥ ባለሙያ",
      ""),
  Employee(
      24,
      "አበራ እሸቱ ማሩ",
      "Abarraa Eshatu Maru",
      "Ogeessa sakatta’iinsa hatattamaa konkolaataa fi mirkaneessa dhaabbilee",
      "",
      "የተሽከርካሪ  ድንገተኛ ምርመራና ተቋማት ብቃት ማረጋገጥ ባለሙያ",
      ""),
  Employee(
      25,
      "ይበልጣል መከተ ሁነኛዉ",
      "Yibelxal Mekete Huneynaw",
      "Daarektarri Tajaajila Hayyama Konkolaachisummaa",
      "ybeltal_meketa.png",
      "የአሽከርካሪ ፈቃድ አገልግሎት ዳይሬክተር",
      ""),
  Employee(
      26,
      "ገለታ በየነ ዱቤ",
      "Galata Bayana Dube",
      "Ogeessa Tajaajila Hayyama Konkolaachisummaa",
      "geleta_beyene.png",
      "የአሽከርከሪ ፈቃድ አገልግሎት ባለሙያ",
      "15"),
  Employee(
      27,
      "ንግስት አየነዉ ሞላ",
      "Nigist Ayanaw Mollaa",
      "Daarektarri Tajaajila Hayyama Konkolaachisummaa",
      "negste_ayene.png",
      "የአሽከርካሪ ፈቃድ አገልግሎት ዳይሬክተር",
      "17"),
  Employee(
      28,
      "መሀመድኑር ሽፋ አሊ",
      "MahammadNur Shifa Ali",
      "Ogeessa Tajaajila Hayyama Konkolaachisummaa",
      "",
      "የአሽከርከሪ ፈቃድ አገልግሎት ባለሙያ",
      "16"),
  Employee(
      29,
      "እዮብ መንግስቱ  ወ/ፃዲቅ",
      "Eyob Mengistu W/Tsadiq",
      "Ogeessa Tajaajila Hayyama Konkolaachisummaa",
      "",
      "የአሽከርከሪ ፈቃድ አገልግሎት ባለሙያ",
      "18"),
  Employee(
      30,
      "ከተማ ረፌራ ቆርቻ",
      "Katama Rafera Qorchaa",
      "Hojjetaa enkoodara daataa konkolaachisaa",
      "",
      "የአሽከርካሪ የዳታ ኢንኮደር ሰራተኛ",
      ""),
  Employee(31, "አረጋሽ ይገዙ ማሞ", "Aragaash Yigazu Mammo",
      "Hojjetaa galmee fi kuusaa", "", "የሪከርድና ማህደር ሠራተኛ", ""),
  Employee(32, "ገነት እንዳለ ተስፋ", "Gannat Endala Tasfaa",
      "Hojjetaa galmee fi kuusaa", "", "የሪከርድና ማህደር ሠራተኛ", ""),
  Employee(33, "ንጉሴ ጣሰዉ ኦቄ", "Nigusee Xaasaw Oqe",
      "Madaallii ti’oorii jalqabaa", "", "የንድፈ ሃሳብ ምዘና እስጀማሪ ባለሙያ ", "32"),
  Employee(
      34,
      "ዝናሽ ደምሴ ንጋዉ",
      "Zinash Damissee Nigaw",
      "Madaallii ti’oorii jalqabaa",
      "zenash_demisse.png",
      "የንድፈ ሃሳብ ምዘና እስጀማሪ ባለሙያ",
      "32"),
  Employee(35, "አለምሸት አበበ ጎንቼ", "Alamishat Ababa Gonchee",
      "Ogeessa odiitii qulqullina tajaajilaa", "", "የአገልግሎት ጥራት ኦዲት ባለሙያ", ""),
  Employee(36, "አዲስ አለማየሁ ደረሱ", "Addisu Alamaayyaw Darasu",
      "Ogeessa odiitii qulqullina tajaajilaa", "", "የአገልግሎት ጥራት ኦዲት ባለሙያ ", ""),
  Employee(37, "ጉርምስ አጥላባቸዉ ንጉሴ", "Gurmsaa Axilaabachaw Niguse",
      "Ogeessa odiitii qulqullina tajaajilaa", "", "የአገልግሎት ጥራት ኦዲት ባለሙያ ", ""),
  Employee(38, "አሸብር አበበ ወንድሙ", "Ashabbiir Ababa Wandimu",
      "Ogeessa odiitii qulqullina tajaajilaa", "", "የአገልግሎት ጥራት ኦዲት ባለሙያ ", ""),
  Employee(39, "እቴነሽ ደንቦላዉ", "Iteenash Danbolaw", "Ogeessa komii furuu", "",
      "የቅሬታ አፈታት  ባለሙያ", ""),
  Employee(
      40,
      "ተክለፃዲቅ አዘነ ወ/ሃዋሪያት",
      "T/Tsadik Azana W/Haawariyat",
      "Daarektarri Bulchiinsa Qabeenya Faayinaansii Bittaa",
      "",
      "የግዥ የፋይናንስ  ንብረት አሰተዳደር ዳይሬክተር",
      "29"),
  Employee(
      41,
      "ገነት ጥበበ ኃ/ጊወርጊስ",
      "Gannat Xibab H/Giyoorgis",
      "Ogeessa karoora, raawwii, hordoffii fi madaallii",
      "",
      "የዕቅድ ዝግጅት፣ አፈጻጸም፣ ክትትልና ግምገማ ባለሙያ",
      "25"),
  Employee(42, "እልፍነሽ ሽፈራዉ መኮንን", "Ilfnash Shiferaw Makonnin",
      "Hogganaa garee faayinaansii", "", "የፋይናንስ ቡድን መሪ", "29"),
  Employee(43, "ብርቱካን እምሬ አያሌዉ", "Birtukan Emire Ayalew", "Herrega", "",
      "አካውንት", ""),
  Employee(44, "እመቤት እጅጉ", "Emabet Ejigu", "Bulachaa Akaawanti Google ", "",
      "ጎግል	አካውንት", ""),
  Employee(45, "ይርገዱ አዳፍሬ ሽፈራዉ", "Yirgadu Adafre Shifaraw", "Herrega", "",
      "አካውንት", ""),
  Employee(46, "ሙላቷ መኮንን ጥላሁን", "Mulatu Makonnin  Xilhaun", "Abbaa herregaa",
      "", "የሒሳብ ሰነድ ያዥ  ", ""),
  Employee(47, "ወ/ር መኳንንት አቦሀይ	", "Makuwaanint Abahoy",
      "Walitti qabaa maallaqa guyyaa", "", "የዕለት ገንዘብ ሰብሳቢ ", "14"),
  Employee(48, "ከተማ ፈየ ጉተማ", "Katama Fayye Gutama",
      " Walitti qabaa maallaqa guyyaa", "", "የዕለት ገንዘብ ሰብሳቢ", "13"),
  Employee(49, "የሺ ኃይሉ ወ/ጊዮርጊስ", "Yashi Hayilu W/Giyoorgis",
      " Walitti qabaa maallaqa guyyaa", "", "የዕለት ገንዘብ ሰብሳቢ ", "12"),
  Employee(50, "ሞላልኝ ነጋ አዳሙ", "Molaaliny Nagga Adaamu",
      " Walitti qabaa maallaqa guyyaa", "", "የዕለት ገንዘብ ሰብሳቢ", ""),
  Employee(51, "ፉፋ ዋቅወያ ገመቹ", "Fafa Waaqqayya Gamachu", "Abbaa seeraa", "",
      "የህግ ባለሙያ ", "33"),
  Employee(
      52,
      "ላገር ጥላሁን ያለዉ",
      "Laagar Xilahun Yalaw",
      "Hogganaa garee raawwii qulqullina tajaajilaa fi komii odiitii",
      "lager_tilhun.png",
      "የአ/ጥራ/",
      "")
];
