class Employee {
  int id;
  String amharic_name;
  String oromic_name;
  String oromic_position;
  String path;
  String position;
  String office;
  Employee(this.id, this.amharic_name, this.oromic_name, this.oromic_position,
      this.path, this.position, this.office);
}

List<Employee> Employees = [
  Employee(1, "ያዜ የሻምበል ታፈረ", "Yaze Yeshamber Terefe", "Hogganaa Damee",
      "shambel_tefera.png", "የቅርንጫፍ ስራ አስኪያጅ", "20"),
  Employee(2, "ታንጉት አእምሮ ፈንታ", "Tangut Aymro Fanta",
      "Barreessaa Hojii Raawwachiiftuu", "tangut.png", "ኤክስኪዩቲቭ ሴክሬታሪ ", "20"),
  Employee(
      3,
      "ጌትነት አድማሱ ጌታሁን",
      "Getnat Admasu Getahun",
      "Daarektarri Tajaajila Mirkaneessuu fi Hayyama Konkolaataa",
      "getnet_admasu.png",
      "የተሸከርካሪ ብቃት ማረጋገጥና ፈቃድ አገልግሎት ዳይሬክተር",
      "21"),
  Employee(
      4,
      "ታምራት አበራ ኃይሌ",
      "Tamirat Abarra Haayile",
      "Hogganaa garee gahumsa konkolaataa",
      "tamirat_abera.png",
      "የተሽከርካሪ  ብቃት ማረጋገጥ ቡድን መሪ",
      "21"),
  Employee(
      5,
      "ይበልጣል መከተ ሁነኛዉ",
      "Yibeltal",
      "Daarektarri Tajaajila Hayyama Konkolaachisummaa fi ICT",
      "ybeltal_meketa.png",
      "የአሽከርካሪ ፈቃድ አገልግሎት ዳይሬክተርና ICT",
      "22"),
  Employee(
      6,
      "ጥላሁን ዴንሳ",
      "Tilahun Densa",
      "Daarektarri naamusaa fi farra malaammaltummaa",
      "tilahun_densa.png",
      "የስነምገባርና ፀረ ሙስና ዳይሬክተር",
      "23"),
  Employee(7, "", "", "Tajaajila copy", "", "የኮፒ አገልግሎት", "24"),
  Employee(
      8,
      "ገነት ጥበበ ኃ/ጊወርጊስ",
      "Gannat Tibaba H/Giyoorgis",
      "Ogeessa karoora, raawwii, hordoffii fi madaallii",
      "genet.png",
      "የዕቅድ ዝግጅት፣ አፈጻጸም፣ ክትትልና ግምገማ ባለሙያ",
      "25"),
  Employee(9, "ይርገዱ አዳፍሬ ሽፈራዉ", "Yirgadu Adafre Shifaraw", "Herrega",
      "yirgadu_adefrs.png", "አካውንት", "28"),
  Employee(10, "ተክለፃዲቅ አዘነ ወ/ሃዋሪያት", "Taklatsadiq Azana W/Hawaryat", "Herrega",
      "tekletsadik.png", "አካውንት", "29"),
  Employee(
      11,
      "ሳሙኤል ግዛዉ ሞረዳ",
      "Samuel Gizaw Moroda",
      "Ogeessa tajaajila odeeffannoo",
      "samuel_gizaw.png",
      "የመረጃ አገልግሎት ባለሙያ ",
      "30"),
  Employee(
      12,
      "ዝናሽ ደምሴ ንጋዉ",
      "Zinash Damissee Nigaw",
      "Piropozaala dizaayinii hayyama konkolaachisummaa qormaata barreeffamaa",
      "zenash_demisse.png",
      "የመንጃ ፈቃድ ንድፍ ሀሳብ የፁሁፍ ፈተና",
      "32"),
  Employee(13, "ፉፋ ዋቅወያ ገመቹ", "Fafa Waaqqayya Gamachu", "Tajaajila seeraa",
      "Fafa.png", "የህግ አገልግሎት", "33"),
  Employee(
      14,
      "ላገር ጥላሁን ያለዉ",
      "Laagar Xilahun Yalaw",
      "Garee odiitii qulqullina tajaajilaa fi furmaata komii",
      "lehager_tilahun.png",
      "የአገልግሎት ጥራት ኦዲትና ቅሬታ አፈታት ቡድን",
      "34"),
  Employee(
      15,
      "እንዳለ ባህሩ ተሰማ",
      "Endale Bahiru Tasamma",
      "Garee gahumsa konkolaataa",
      "endale_birhanu.png",
      "የተሸከርካሪ ብቃት ማረጋገጥ ቡድን",
      "35"),
  Employee(16, "ሚሊዮን አዲሱ በላይ", "Miliyon Addisu Balay ", "Galmee", "biro_36.png",
      "መዝገብ ቤት", "36"),
];

List<Employee> EmployeesRated = [
  Employee(1, "ያዜ የሻምበል ታፈረ", "Yaze Yeshamber Terefe", "Hogganaa Damee",
      "shambel_tefera.png", "የቅርንጫፍ ስራ አስኪያጅ", "20"),
  Employee(2, "ታንጉት አእምሮ ፈንታ", "Tangut Aymro Fanta",
      "Barreessaa Hojii Raawwachiiftuu", "tangut.png", "ኤክስኪዩቲቭ ሴክሬታሪ ", "20"),
  Employee(
      3,
      "ጌትነት አድማሱ ጌታሁን",
      "Getnat Admasu Getahun",
      "Daarektarri Tajaajila Mirkaneessuu fi Hayyama Konkolaataa",
      "getnet_admasu.png",
      "የተሸከርካሪ ብቃት ማረጋገጥና ፈቃድ አገልግሎት ዳይሬክተር",
      "21"),
  Employee(
      4,
      "ታምራት አበራ ኃይሌ",
      "Tamirat Abarra Haayile",
      "Hogganaa garee gahumsa konkolaataa",
      "tamirat_abera.png",
      "የተሽከርካሪ  ብቃት ማረጋገጥ ቡድን መሪ",
      "21"),
  Employee(
      5,
      "ይበልጣል መከተ ሁነኛዉ",
      "Yibeltal",
      "Daarektarri Tajaajila Hayyama Konkolaachisummaa fi ICT",
      "ybeltal_meketa.png",
      "የአሽከርካሪ ፈቃድ አገልግሎት ዳይሬክተርና ICT",
      "22"),
  // Employee(
  //     6,
  //     "ጥላሁን ዴንሳ",
  //     "Tilahun Densa",
  //     "Daarektarri naamusaa fi farra malaammaltummaa",
  //     "tilahun_densa.png",
  //     "የስነምገባርና ፀረ ሙስና ዳይሬክተር",
  //     "23"),
  // Employee(7, "", "", "Tajaajila copy", "", "የኮፒ አገልግሎት", "24"),
  // Employee(
  //     8,
  //     "ገነት ጥበበ ኃ/ጊወርጊስ",
  //     "Gannat Tibaba H/Giyoorgis",
  //     "Ogeessa karoora, raawwii, hordoffii fi madaallii",
  //     "genet.png",
  //     "የዕቅድ ዝግጅት፣ አፈጻጸም፣ ክትትልና ግምገማ ባለሙያ",
  //     "25"),
  // Employee(9, "ይርገዱ አዳፍሬ ሽፈራዉ", "Yirgadu Adafre Shifaraw", "Herrega",
  //     "yirgadu_adefrs.png", "አካውንት", "28"),
  Employee(10, "ተክለፃዲቅ አዘነ ወ/ሃዋሪያት", "Taklatsadiq Azana W/Hawaryat", "Herrega",
      "tekletsadik.png", "አካውንት", "29"),
  Employee(
      11,
      "ሳሙኤል ግዛዉ ሞረዳ",
      "Samuel Gizaw Moroda",
      "Ogeessa tajaajila odeeffannoo",
      "samuel_gizaw.png",
      "የመረጃ አገልግሎት ባለሙያ ",
      "30"),
  Employee(
      12,
      "ዝናሽ ደምሴ ንጋዉ",
      "Zinash Damissee Nigaw",
      "Piropozaala dizaayinii hayyama konkolaachisummaa qormaata barreeffamaa",
      "zenash_demisse.png",
      "የመንጃ ፈቃድ ንድፍ ሀሳብ የፁሁፍ ፈተና",
      "32"),
  Employee(13, "ፉፋ ዋቅወያ ገመቹ", "Fafa Waaqqayya Gamachu", "Tajaajila seeraa",
      "Fafa.png", "የህግ አገልግሎት", "33"),
  Employee(
      14,
      "ላገር ጥላሁን ያለዉ",
      "Laagar Xilahun Yalaw",
      "Garee odiitii qulqullina tajaajilaa fi furmaata komii",
      "lehager_tilahun.png",
      "የአገልግሎት ጥራት ኦዲትና ቅሬታ አፈታት ቡድን",
      "34"),
  Employee(
      15,
      "እንዳለ ባህሩ ተሰማ",
      "Endale Bahiru Tasamma",
      "Garee gahumsa konkolaataa",
      "endale_birhanu.png",
      "የተሸከርካሪ ብቃት ማረጋገጥ ቡድን",
      "35"),
  Employee(16, "ሚሊዮን አዲሱ በላይ", "Miliyon Addisu Balay ", "Galmee", "biro_36.png",
      "መዝገብ ቤት", "36"),
  Employee(
    17,
    "መልካምሰዉ አቤ መንግስቱ",
    "MalkamSaw Abbe Mengistu",
    "Ogeessa tajaajila hayyama konkolaataa",
    "melkam_sewu.png",
    "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
    "5",
  ),
  Employee(
      18,
      "አዳነች ጌጡ መብራቴ",
      "Adanach Gexu Mabrate",
      "Ogeessa tajaajila hayyama konkolaataa",
      "adanech_getu.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
      "8"),
  Employee(
      19,
      "አሚር በህጃ ናስር",
      "Amir Bahaj Nasir",
      "Ogeessa tajaajila hayyama konkolaataa",
      "amir_behaj.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
      "4"),
  Employee(
      20,
      "ታደለ አባተ ካሳ",
      "Tadele Abate Kasa",
      "Ogeessa tajaajila hayyama konkolaataa",
      "tadla_abate.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
      "7"),
  Employee(
      21,
      "ኤደን ተ/ሃይማኖት ኃይሌ",
      "Edan T/Hayimanot Hayile",
      "Ogeessa tajaajila hayyama konkolaataa",
      "eden_tekle.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
      "10"),
  Employee(
      22,
      "ህብስት አድማሱ አድገህ",
      "Hibist Admaasu Adgah",
      "Ogeessa tajaajila hayyama konkolaataa",
      "hibest_admasu.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ ",
      "9"),
  Employee(
      23,
      "ፈድሉ ኑረዲን መሀመድ",
      "Fadila Nuradin Mahammad",
      "Ogeessa qorannoo teeknikaa konkolaataa",
      "fedle_nuredin.png",
      "የተሽከርካሪ የቴክኒክ ምርመራ ባለሙያ ",
      "11"),
  Employee(
      24,
      "ቤተልሄም ጥላሁን ወ/ጊዮርጊስ",
      "Betlihem Xilahun W/Giorgis",
      "Ogeessa qorannoo teeknikaa konkolaataa",
      "bethelhem.png",
      "የተሽከርካሪ የቴክኒክ ምርመራ ባለሙያ ",
      "11"),
  Employee(
      25,
      "ቤኩማ ገመቺስ ሂርጳ",
      "Beekuma Gammmachiis Hirphoo",
      "Ogeessa qorannoo teeknikaa konkolaataa",
      "bekuma.png",
      "የተሽከርካሪ የቴክኒክ ምርመራ ባለሙያ ",
      "11"),
  Employee(
      26,
      "መዓዛ አምሳሉ ቸሩ",
      "Meaza Amsalu Cheru",
      "Ogeessa qorannoo teeknikaa konkolaataa",
      "meaza_amsalu.png",
      "የተሽከርካሪ የቴክኒክ ምርመራ ባለሙያ ",
      "11"),
  Employee(
      27,
      "ቃልኪዳን አሊ አህመድ",
      "Qaalkidaan Ali Ahmad",
      "Qindeessaa Deetaa Konkolaataa / Encoderii Deetaa",
      "kalkidan_ali.png",
      "የተሸከርካሪ መረጃ አጠናቃሪ ባለሙያ/ የዳታ ኢንኮደር ባለሙያ ",
      "34"),
  Employee(
      28,
      "ጀማል ባርቀዳ በሽር",
      "Jamal Barqada Bashir",
      "Bulchaa Kuusaa Deetaa fi Sirna",
      "jamal.png",
      "ዳታ ቤዝ እና ሲስተም አድሚኒስትሬተር ",
      "22"),
  // Employee(
  //     29,
  //     "ነጋ ብሩክ ሀብቴ",
  //     "Naggaa Biruk Habtee",
  //     "Ogeessa sakatta’iinsa hatattamaa konkolaataa fi mirkaneessa dhaabbilee",
  //     "",
  //     "የተሽከርካሪ  ድንገተኛ ምርመራና ተቋማት ብቃት ማረጋገጥ ባለሙያ",
  //     ""),
  Employee(
      30,
      "አበራ እሸቱ ማሩ",
      "Abarraa Eshatu Maru",
      "Ogeessa sakatta’iinsa hatattamaa konkolaataa fi mirkaneessa dhaabbilee",
      "abera.png",
      "የተሽከርካሪ  ድንገተኛ ምርመራና ተቋማት ብቃት ማረጋገጥ ባለሙያ",
      "11"),
  // Employee(
  //     31,
  //     "ይበልጣል መከተ ሁነኛዉ",
  //     "Yibelxal Mekete Huneynaw",
  //     "Daarektarri Tajaajila Hayyama Konkolaachisummaa",
  //     "ybeltal_meketa.png",
  //     "የአሽከርካሪ ፈቃድ አገልግሎት ዳይሬክተር",
  //     "22"),
  Employee(
      32,
      "ገለታ በየነ ዱቤ",
      "Galata Bayana Dube",
      "Ogeessa Tajaajila Hayyama Konkolaachisummaa",
      "geleta_beyene.png",
      "የአሽከርከሪ ፈቃድ አገልግሎት ባለሙያ",
      "15"),
  // Employee(33, "አለምሸት አበበ ጎንቼ", "Alamishat Ababa Gonchee",
  //     "Ogeessa odiitii qulqullina tajaajilaa", "", "የአገልግሎት ጥራት ኦዲት ባለሙያ", ""),
  // Employee(34, "አዲስ አለማየሁ ደረሱ", "Addisu Alamaayyaw Darasu",
  //     "Ogeessa odiitii qulqullina tajaajilaa", "", "የአገልግሎት ጥራት ኦዲት ባለሙያ ", ""),
  // Employee(35, "ጉርምስ አጥላባቸዉ ንጉሴ", "Gurmsaa Axilaabachaw Niguse",
  //     "Ogeessa odiitii qulqullina tajaajilaa", "", "የአገልግሎት ጥራት ኦዲት ባለሙያ ", ""),
  // Employee(36, "አሸብር አበበ ወንድሙ", "Ashabbiir Ababa Wandimu",
  //     "Ogeessa odiitii qulqullina tajaajilaa", "", "የአገልግሎት ጥራት ኦዲት ባለሙያ ", ""),
  // Employee(37, "እቴነሽ ደንቦላዉ", "Iteenash Danbolaw", "Ogeessa komii furuu", "",
  //     "የቅሬታ አፈታት  ባለሙያ", ""),
  // Employee(
  //     38,
  //     "ተክለፃዲቅ አዘነ ወ/ሃዋሪያት",
  //     "T/Tsadik Azana W/Haawariyat",
  //     "Daarektarri Bulchiinsa Qabeenya Faayinaansii Bittaa",
  //     "",
  //     "የግዥ የፋይናንስ  ንብረት አሰተዳደር ዳይሬክተር",
  //     "29"),
  Employee(39, "እልፍነሽ ሽፈራዉ መኮንን", "Ilfnash Shiferaw Makonnin",
      "Hogganaa garee faayinaansii", "elfnesh.png", "የፋይናንስ ቡድን መሪ", "29"),
  // Employee(40, "ብርቱካን እምሬ አያሌዉ", "Birtukan Emire Ayalew", "Herrega", "",
  //     "አካውንት", ""),
  // Employee(41, "እመቤት እጅጉ", "Emabet Ejigu", "Bulachaa Akaawanti Google ", "",
  //     "ጎግል አካውንት", ""),
  // Employee(42, "ሙላቷ መኮንን ጥላሁን", "Mulatu Makonnin  Xilhaun", "Abbaa herregaa",
  //     "", "የሒሳብ ሰነድ ያዥ  ", ""),
  Employee(
      43,
      "ወ/ር መኳንንት አቦሀይ	",
      "Makuwaanint Abahoy",
      "Walitti qabaa maallaqa guyyaa",
      "mekuanint.png",
      "የዕለት ገንዘብ ሰብሳቢ ",
      "14"),
  Employee(
    44,
    "ከተማ ፈየ ጉተማ",
    "Katama Fayye Gutama",
    " Walitti qabaa maallaqa guyyaa",
    "ketema.png",
    "የዕለት ገንዘብ ሰብሳቢ",
    "13",
  ),
  Employee(45, "የሺ ኃይሉ ወ/ጊዮርጊስ", "Yashi Hayilu W/Giyoorgis",
      " Walitti qabaa maallaqa guyyaa", "yeshi.png", "የዕለት ገንዘብ ሰብሳቢ ", "12"),
  Employee(46, "ሞላልኝ ነጋ አዳሙ", "Molaaliny Nagga Adaamu",
      " Walitti qabaa maallaqa guyyaa", "molalign.png", "የዕለት ገንዘብ ሰብሳቢ", "12"),
  Employee(
      47,
      "ንግስት አየነዉ ሞላ",
      "Nigist Ayanaw Mollaa",
      "Daarektarri Tajaajila Hayyama Konkolaachisummaa",
      "negste_ayene.png",
      "የአሽከርካሪ ፈቃድ አገልግሎት ዳይሬክተር",
      "17"),
  Employee(
      48,
      "መሀመድኑር ሽፋ አሊ",
      "MahammadNur Shifa Ali",
      "Ogeessa Tajaajila Hayyama Konkolaachisummaa",
      "mehamed.png",
      "የአሽከርከሪ ፈቃድ አገልግሎት ባለሙያ",
      "16"),
  Employee(
      49,
      "እዮብ መንግስቱ  ወ/ፃዲቅ",
      "Eyob Mengistu W/Tsadiq",
      "Ogeessa Tajaajila Hayyama Konkolaachisummaa",
      "eyob.png",
      "የአሽከርከሪ ፈቃድ አገልግሎት ባለሙያ",
      "18"),
  // Employee(
  //     50,
  //     "ከተማ ረፌራ ቆርቻ",
  //     "Katama Rafera Qorchaa",
  //     "Hojjetaa enkoodara daataa konkolaachisaa",
  //     "",
  //     "የአሽከርካሪ የዳታ ኢንኮደር ሰራተኛ",
  //     ""),
  // Employee(51, "አረጋሽ ይገዙ ማሞ", "Aragaash Yigazu Mammo",
  //     "Hojjetaa galmee fi kuusaa", "", "የሪከርድና ማህደር ሠራተኛ", ""),
  Employee(52, "ንጉሴ ጣሰዉ ኦቄ", "Nigusee Xaasaw Oqe",
      "Madaallii ti’oorii jalqabaa", "", "የንድፈ ሃሳብ ምዘና እስጀማሪ ባለሙያ ", "32"),
  Employee(
      53,
      "ዋሲሁን መላኩ ባህሩ",
      "Wasihun Malaku Bahiru",
      "Oggessa Haayyama Konkolaataa",
      "wasihun_melaku.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ",
      "6"),
  Employee(
      54,
      "ሃብታሙ ወርቃለም አሊ",
      "Habtamu Warqaalama Ali",
      "Oggessa Haayyama Konkolaataa",
      "habtamu_werkalema.png",
      "የተሽከርካሪ ፈቃድ አገልግሎት ባለሙያ",
      "3"),
  Employee(
      55,
      "ኤልያስ ስርዓቱ ፉጃጋ",
      "Eliyas Siri'atu Fajiga",
      "Ogeessa qorannoo teeknikaa konkolaataa",
      "eliyas.jpg",
      "የተሽከርካሪ የቴክኒክ ምርመራ ባለሙያ",
      "11"),
];
